import type { NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";
// import CharacterSelection from '../components/characterSelection';

const Home: NextPage = () => {
  const [xCord, setXCord] = useState(0);
  const [yCord, setYCord] = useState(0);
  const [pageX, setPageX] = useState(0);
  const [pageY, setPageY] = useState(0);
  const [isOpen, setIsOpen] = useState(false);
  const [isMonkey, setIsMonkey] = useState(false);
  const [isLink, setIsLink] = useState(false);
  const [isLuigi, setIsLuigi] = useState(false);
  const [isMonkeyClicked, setIsMonkeyClicked] = useState(false);
  const [isLinkClicked, setIsLinkClicked] = useState(false);
  const [isLuigiClicked, setIsLuigiClicked] = useState(false);

  const selectionHandler = () => {
    if(pageX >= 20 && pageX <= 27 && pageY >= 43 && pageY <= 46){
      setIsMonkey(true);
    }
    else if(pageY >= 48 && pageY <= 51 && pageX >= 79 && pageX <= 84){
      setIsLuigi(true);
    }
    else if(pageY >= 65 && pageY <= 68 && pageX >= 64 && pageX <= 73){
      setIsLink(true);
    }
    setIsOpen(!isOpen);
  };

  const mouseHandler = (e: any) => {
    setPageX(
      Math.round(
        (e.nativeEvent.offsetX / e.nativeEvent.target.offsetWidth) * 100
      )
    );
    setPageY(
      Math.round(
        (e.nativeEvent.offsetY / e.nativeEvent.target.offsetHeight) * 100
      )
    );
  };

  const monkeyHandler = () => {
    if(!isMonkeyClicked && isMonkey){
      setIsMonkeyClicked(true);
      alert("you found Monkey");
    }
    else if(!isMonkeyClicked && !isMonkey){
      alert("thats not Monkey")
    }
    else if(isMonkeyClicked){
      alert("you already found Monkey Ball")
    }
  }

  const luigiHandler = () => {
    if(!isLuigiClicked && isLuigi){
      setIsLuigiClicked(true);
      alert("you found    Luigi");
    }
    else if(!isLuigiClicked && !isLuigi){
      alert("thats not Luigi")
    }
    else if(isLuigiClicked){
      alert("you already found Luigi")
    }


  }

  const linkHandler = () => {
    if(!isLinkClicked && isLink){
      setIsLinkClicked(true);
      alert("you found Link");
    }
    else if(!isLinkClicked && !isLink){
      alert("thats not Link")
    }
    else if(isLinkClicked){
      alert("you already found Link")
    }
  }


  return (
    <div
      onMouseMove={mouseHandler}
      onClick={selectionHandler}
      className="flex home"
    >
      <Head>
        <title>Where is Everyone?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx>{`.items-container{
    top: ${yCord - 20}px;
    left: ${xCord + 25}px;`}</style>

      {isOpen ? (
        <div
          className='rounded-md  bg-zinc-100 text-2xl font-semibold absolute items-container cursor-pointer shadow-md'
        >
          <h1 className={(isLuigiClicked ? "line-through" : "") + "border-black border-b-2 hover:bg-zinc-300 p-2 rounded-t-md"} onClick={luigiHandler}>Luigi</h1>
          <h1 className="border-black border-b-2 p-2 hover:bg-zinc-300" onClick={linkHandler}>Link</h1>
          <h1 className="p-2 rounded-b-md hover:bg-zinc-300" onClick={monkeyHandler}>Monkey Ball</h1>
        </div>
      ) : (
        <></>
      )}

      {/* <div className="flex flex-col gap-5 text-rose-400 text-3xl fixed top-10 left-10">
        <h1>X: {xCord}</h1>
        <h1>Y: {yCord}</h1>
        <h1>page X: {pageX}</h1>
        <h1>page Y: {pageY}</h1>
      </div> */}
    </div>
  );
};

export default Home;
